"""Builds the three self-contained Kaggle task files in build/.

Each task file = imports + the embedded ground truth + the grader + the task.
Before writing, every gold answer and required name is checked against the
ground truth, so a typo can never become a wrong benchmark answer.
"""
import ast
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).parent
SRC = ROOT / "src"
OUT = ROOT / "build"
OUT.mkdir(exist_ok=True)

data = (SRC / "semconv.json").read_text()
index = {(r["k"], r["n"]): r for r in json.loads(data)}
grader = (SRC / "grader.py").read_text().replace("import json\nimport re\n", "")


def current(kind, name):
    row = index.get((kind, name))
    return row is not None and row["s"] == "c"


def check_know(source):
    tree = ast.parse(source)
    questions = next(n.value for n in tree.body if isinstance(n, ast.Assign) and n.targets[0].id == "QUESTIONS")
    for qid, text, gold, unit in ast.literal_eval(questions):
        old = re.findall(r"[a-z][a-z0-9_]*(?:\.[a-z0-9_]+)+", text)[0]
        kind = "m" if "metric" in text else "a"
        row = index[(kind, old)]
        answers = [n for g in gold for n in re.findall(r"[a-z][a-z0-9_]*(?:\.[a-z0-9_]+)+", g)]
        for a in answers:
            assert current(kind, a), f"{qid}: gold {a} is not a current {kind} name"
        if qid.startswith("control_"):
            assert row["s"] == "c" and answers == [old], f"{qid}: control must be an unchanged current name"
        elif row["s"] == "x":
            pass  # dropped: the gold comes from the migration guide, verified by hand in kb/DECISIONS.md
        else:
            assert set(answers) <= set(row.get("r", [])), f"{qid}: {answers} not in dataset replacements {row.get('r')}"
        if unit:
            assert index[("m", answers[0])].get("u") == unit, f"{qid}: unit {unit} disagrees with the dataset"
    return len(ast.literal_eval(questions))


def check_fix(source):
    tree = ast.parse(source)
    cases = next(n.value for n in tree.body if isinstance(n, ast.Assign) and n.targets[0].id == "CASES")
    for cid, _lang, _code, required, _check in ast.literal_eval(cases):
        for name in required:
            kind = "m" if any(index.get(("m", name), {}).get("s") == "c" for _ in [0]) else "a"
            assert current(kind, name), f"{cid}: required {name} is not current"
    return len(ast.literal_eval(cases))


for name in ["write", "know", "fix"]:
    body = (SRC / f"task_{name}.py").read_text()
    if name == "know":
        n = check_know(body)
    elif name == "fix":
        n = check_fix(body)
    else:
        tree = ast.parse(body)
        n = len(ast.literal_eval(next(x.value for x in tree.body if isinstance(x, ast.Assign) and x.targets[0].id == "CASES")))
    head, _, rest = body.partition("\n\n")
    header = "\n".join(l for l in body.splitlines() if l.startswith(("import ", "from ")))
    without_imports = "\n".join(l for l in body.splitlines() if not l.startswith(("import ", "from ")))
    out = (
        f"{head.splitlines()[0]}\n"
        "# Generated by build.py from https://github.com/vignesh2027/semconv-drift. Ground truth: the public\n"
        "# Attrition dataset (Sanity project y9raau23), OpenTelemetry semantic conventions v1.21.0 to v1.44.0.\n"
        "import json\nimport re\n"
        f"{header}\n\n"
        f"DATA_JSON = {json.dumps(data)}\n\n"
        f"{grader}\n\n"
        f"{without_imports.split(chr(10), 1)[1].lstrip()}"
    )
    compile(out, name, "exec")
    (OUT / f"semconv_drift_{name}.py").write_text(out)
    print(f"build/semconv_drift_{name}.py  {len(out)//1024} KB  checked {n} items")
